# Generated by Django 5.2.5 on 2025-08-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('phone_number', models.CharField(default='', max_length=200)),
                ('profile_image', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
